In [8]:
import pandas as pd

In [9]:
df = pd.read_csv("/content/Sample - Superstore.csv", encoding='windows-1252')

In [10]:

df.to_excel("Superstore_Project_Data.xlsx", index=False)

In [11]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [13]:
df.describe(include='all')

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994,9994,9994,9994,9994,9994,9994,9994,...,9994.000000,9994,9994,9994,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000
unique,NaN,5009,1237,1334,4,793,793,3,1,531,...,NaN,4,1862,3,17,1850,NaN,NaN,NaN,NaN
top,NaN,CA-2017-100111,9/5/2016,12/16/2015,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,...,NaN,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope,NaN,NaN,NaN,NaN
freq,NaN,14,38,35,5968,37,37,5191,9994,915,...,NaN,3203,19,6026,1523,48,NaN,NaN,NaN,NaN
mean,4997.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,55190.379428,NaN,NaN,NaN,NaN,NaN,229.858001,3.789574,0.156203,28.656896
std,2885.163629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32063.693350,NaN,NaN,NaN,NaN,NaN,623.245101,2.225110,0.206452,234.260108
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1040.000000,NaN,NaN,NaN,NaN,NaN,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23223.000000,NaN,NaN,NaN,NaN,NaN,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56430.500000,NaN,NaN,NaN,NaN,NaN,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,90008.000000,NaN,NaN,NaN,NaN,NaN,209.940000,5.000000,0.200000,29.364000
max,9994.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99301.000000,NaN,NaN,NaN,NaN,NaN,22638.480000,14.000000,0.800000,8399.976000

In [14]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [15]:
df.columns = [c.replace(' ', '_').replace('-', '_') for c in df.columns]

In [16]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df['Ship_Date'] = pd.to_datetime(df['Ship_Date'])

In [17]:
if 'Review_Rating' in df.columns:
    df['Review_Rating'] = df.groupby('Category')['Review_Rating'].transform(lambda x: x.fillna(x.median()))

In [18]:
df.drop_duplicates(inplace=True)

In [19]:
df['Profit_Margin'] = (df['Profit'] / df['Sales']) * 100

In [20]:
import sqlite3
conn = sqlite3.connect('superstore_db')
df.to_sql('sales_table', conn, if_exists='replace', index=False)

9994

In [21]:
conn = sqlite3.connect('superstore_analytics.db')

In [22]:
df.to_sql('orders', conn, if_exists='replace', index=False)

9994

In [23]:
print("Table 'orders') created successfully.")

Table 'orders') created successfully.

In [24]:


query_region = """
SELECT Region, SUM(Sales) as Total_Sales, SUM(Profit) as Total_Profit
FROM orders
GROUP BY Region
ORDER BY Total_Profit DESC;
"""
region_df = pd.read_sql(query_region, conn)
print("--- Region Performance ---")
display(region_df)

--- Region Performance ---

    Region  Total_Sales  Total_Profit
0     West  725457.8245   108418.4489
1     East  678781.2400    91522.7800
2    South  391721.9050    46749.4303
3  Central  501239.8908    39706.3625

In [25]:

query_loyalty = """
SELECT Customer_ID, Customer_Name, COUNT(Order_ID) as Frequency, SUM(Sales) as Total_Revenue
FROM orders
GROUP BY Customer_ID, Customer_Name
ORDER BY Frequency DESC
LIMIT 10;
"""

loyalty_df = pd.read_sql(query_loyalty, conn)
print(loyalty_df)

  Customer_ID        Customer_Name  Frequency  Total_Revenue
0    WB-21850        William Brown         37      6160.1020
1    JL-15835             John Lee         34      9799.9230
2    MA-17560         Matt Abelman         34      4299.1610
3    PP-18955           Paul Prost         34      7252.6080
4    CK-12205  Chloris Kastensmidt         32      3154.8550
5    EH-13765         Edward Hooks         32     10310.8800
6    JD-15895     Jonathan Doherty         32      7610.8640
7    SV-20365          Seth Vernon         32     11470.9500
8    AP-10915       Arthur Prichep         31      3323.5560
9    EP-13915           Emily Phan         31      5478.0608

In [26]:
query_segments = """
SELECT Segment,
       COUNT(Order_ID) as Total_Orders,
       SUM(Sales) as Revenue,
       AVG(Discount) as Avg_Discount
FROM orders
GROUP BY Segment
ORDER BY Revenue DESC;
"""
segment_df = pd.read_sql(query_segments, conn)
print("--- Customer Segment Analysis ---")

display(segment_df)

--- Customer Segment Analysis ---

       Segment  Total_Orders       Revenue  Avg_Discount
0     Consumer          5191  1.161401e+06      0.158141
1    Corporate          3020  7.061464e+05      0.158228
2  Home Office          1783  4.296531e+05      0.147128

In [27]:
df.to_csv('cleaned_superstore_final.csv', index=False)

In [28]:
data_cleaning.ipy

NameError: name 'data_cleaning' is not defined

In [ ]:
from google.colab import drive
drive.mount('/content/drive')